### PR TITLE
fix index-list async issue

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow the contributing guide.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
#308

**Comment by eleven-ng** [comment]
mint ui 2.0.2有没用修复此bug？

**Comment by Leopoldthecoder** [comment]
@eleven-ng 会在 2.0.3 包含此修复。

**Comment by eleven-ng** [comment]
发布时间大概是什么时候

**Comment by Leopoldthecoder** [comment]
本周应该会发

**Comment by ibmsoft** [comment]
今天（2016-10-28）更新到 2.0.4，问题依旧呢

**Pull request merged**
