### PR TITLE
add ssr support

### PR DESCRIPTION
**Pull request by yuchonghua**
add ssr support
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow the contributing guide.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

[add ssr more](https://github.com/ElemeFE/mint-ui/issues/548)

### CODE REVIEW

**Comment by yuchonghua** [comment]
@QingWei-Li 请检测一下

**Comment by yuchonghua** [comment]
@QingWei-Li

**Comment by yuchonghua** [comment]
谢谢

**Comment by yuchonghua** [comment]
大概多久才可以发布下载呢

**Comment by yuchonghua** [comment]
@QingWei-Li @Leopoldthecoder 您好，大概什么时候方便发布一下呢？

**Comment by yuchonghua** [comment]
@ Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
两个 merge.js？

**Comment by yuchonghua** [comment]
两个 merge.js 是指？

**Comment by yuchonghua** [comment]
就目前这个才是 pr

**Comment by yuchonghua** [comment]
其他的都关闭了

**Comment by yuchonghua** [comment]
@Leopoldthecoder 
两个 merge.js 是指？
就目前这个才是 pr
其他的都关闭了

**Comment by yuchonghua** [comment]
懂你意思了，src/merge.js这个是没有用到的

**Comment by Leopoldthecoder** [comment]
没用到的那个删掉吧

**Comment by yuchonghua** [comment]
删掉了，我该如何Rebase before creating a PR to keep commit history clear.

**Comment by yuchonghua** [comment]
@Leopoldthecoder ok
已经 删除 并且 Rebase before creating a PR to keep commit history clear.

**Comment by yuchonghua** [comment]
我可以删除那个fork了吗

**Comment by yuchonghua** [comment]
大概什么时候可以推到npm呢？

**Pull request merged**
